services:
  postgresql:
    container_name: pio_postgres
    image: postgres:16.0-alpine
    ports:
      - 5432:5432
    volumes:
      - pio_postgresql:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=admin
    - POSTGRES_USER=admin
    - POSTGRES_DB=pio
    networks:
      - pio_network
    healthcheck:
      test: pg_isready -U admin -d pio
      interval: 2s
      timeout: 3s
      retries: 5
  
  webserver:
    container_name: pio_webserver
    image: pio_webserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 6060:6060
    volumes:
    - ./:/app
    command: ["npm", "run", "start:dev"]
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - pio_network

networks:
  pio_network:
    name: pio_network
    driver: bridge

volumes:
  pio_postgresql:
    name: pio_postgresql